### ISSUE TITLE
Is this project equivalent to Kickstart?

### ISSUE THREAD

**Issue by mooreds** [FilipMalczak/fusionauth-x#2]
Hiya,

This project definitely fulfilled a need when you created it. 

I was wondering if you'd looked at Kickstart (docs: https://fusionauth.io/docs/v1/tech/installation-guide/kickstart )? From my brief look at fusionauth-x, it seems like there is substantial overlap.

I'm an employee of FusionAuth FWIW.

**Comment by FilipMalczak** [comment]
@mooreds Thank you for bringing this to my attention. Seems like Kickstart does everything that this was supposed to do, but better. I will modify the README and freeze the repo to route people to Kickstart.
